# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(545, 621)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 531, 251))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stopButton = QtGui.QPushButton(self.layoutWidget)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.gridLayout.addWidget(self.stopButton, 3, 0, 1, 1)
        self.resetButton = QtGui.QPushButton(self.layoutWidget)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout.addWidget(self.resetButton, 1, 1, 1, 1)
        self.blankButton = QtGui.QPushButton(self.layoutWidget)
        self.blankButton.setObjectName(_fromUtf8("blankButton"))
        self.gridLayout.addWidget(self.blankButton, 3, 1, 1, 1)
        self.pauseButton = QtGui.QPushButton(self.layoutWidget)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.gridLayout.addWidget(self.pauseButton, 0, 0, 1, 1)
        self.undockButton = QtGui.QPushButton(self.layoutWidget)
        self.undockButton.setObjectName(_fromUtf8("undockButton"))
        self.gridLayout.addWidget(self.undockButton, 2, 0, 1, 1)
        self.dockButton = QtGui.QPushButton(self.layoutWidget)
        self.dockButton.setObjectName(_fromUtf8("dockButton"))
        self.gridLayout.addWidget(self.dockButton, 2, 1, 1, 1)
        self.turnButton = QtGui.QPushButton(self.layoutWidget)
        self.turnButton.setObjectName(_fromUtf8("turnButton"))
        self.gridLayout.addWidget(self.turnButton, 1, 0, 1, 1)
        self.gobutton = QtGui.QPushButton(self.layoutWidget)
        self.gobutton.setObjectName(_fromUtf8("gobutton"))
        self.gridLayout.addWidget(self.gobutton, 0, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 270, 531, 217))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.srcLabel = QtGui.QLabel(self.layoutWidget1)
        self.srcLabel.setObjectName(_fromUtf8("srcLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.srcLabel)
        self.dstLabel = QtGui.QLabel(self.layoutWidget1)
        self.dstLabel.setObjectName(_fromUtf8("dstLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dstLabel)
        self.srclistWidget = QtGui.QListWidget(self.layoutWidget1)
        self.srclistWidget.setMaximumSize(QtCore.QSize(323, 16777215))
        self.srclistWidget.setObjectName(_fromUtf8("srclistWidget"))
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.srclistWidget.addItem(item)
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.srclistWidget)
        self.dstlistWidget = QtGui.QListWidget(self.layoutWidget1)
        self.dstlistWidget.setObjectName(_fromUtf8("dstlistWidget"))
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.dstlistWidget.addItem(item)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dstlistWidget)
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(90, 500, 151, 111))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineLabel = QtGui.QLabel(self.layoutWidget2)
        self.lineLabel.setObjectName(_fromUtf8("lineLabel"))
        self.verticalLayout.addWidget(self.lineLabel)
        self.stateLabel = QtGui.QLabel(self.layoutWidget2)
        self.stateLabel.setObjectName(_fromUtf8("stateLabel"))
        self.verticalLayout.addWidget(self.stateLabel)
        self.intersectionLabel = QtGui.QLabel(self.layoutWidget2)
        self.intersectionLabel.setObjectName(_fromUtf8("intersectionLabel"))
        self.verticalLayout.addWidget(self.intersectionLabel)
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(380, 500, 61, 101))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.batteryLabel = QtGui.QLabel(self.layoutWidget3)
        self.batteryLabel.setObjectName(_fromUtf8("batteryLabel"))
        self.verticalLayout_2.addWidget(self.batteryLabel)
        self.modeLabel = QtGui.QLabel(self.layoutWidget3)
        self.modeLabel.setObjectName(_fromUtf8("modeLabel"))
        self.verticalLayout_2.addWidget(self.modeLabel)
        self.sonarLabel = QtGui.QLabel(self.layoutWidget3)
        self.sonarLabel.setObjectName(_fromUtf8("sonarLabel"))
        self.verticalLayout_2.addWidget(self.sonarLabel)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.srclistWidget, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), Dialog.srcListItemClicked)
        QtCore.QObject.connect(self.dstlistWidget, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), Dialog.dstListItemClicked)
        QtCore.QObject.connect(self.pauseButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.pauseButtonPressed)
        QtCore.QObject.connect(self.resetButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.resetButtonPressed)
        QtCore.QObject.connect(self.stopButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.stopButtonPressed)
        QtCore.QObject.connect(self.dockButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.dockButtonPressed)
        QtCore.QObject.connect(self.undockButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.undockButtonPressed)
        QtCore.QObject.connect(self.blankButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.blankButtonPressed)
        QtCore.QObject.connect(self.turnButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.turnButtonPressed)
        QtCore.QObject.connect(self.gobutton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.goButtonPressed)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.stopButton.setText(_translate("Dialog", "STOP", None))
        self.resetButton.setText(_translate("Dialog", "RESET", None))
        self.blankButton.setText(_translate("Dialog", "BLANK", None))
        self.pauseButton.setText(_translate("Dialog", "PAUSE", None))
        self.undockButton.setText(_translate("Dialog", "UNDOCK", None))
        self.dockButton.setText(_translate("Dialog", "DOCK", None))
        self.turnButton.setText(_translate("Dialog", "TURN", None))
        self.gobutton.setText(_translate("Dialog", "GO", None))
        self.srcLabel.setText(_translate("Dialog", "Source", None))
        self.dstLabel.setText(_translate("Dialog", "Destination", None))
        __sortingEnabled = self.srclistWidget.isSortingEnabled()
        self.srclistWidget.setSortingEnabled(False)
        item = self.srclistWidget.item(0)
        item.setText(_translate("Dialog", "A", None))
        item = self.srclistWidget.item(1)
        item.setText(_translate("Dialog", "B", None))
        item = self.srclistWidget.item(2)
        item.setText(_translate("Dialog", "C", None))
        item = self.srclistWidget.item(3)
        item.setText(_translate("Dialog", "D", None))
        item = self.srclistWidget.item(4)
        item.setText(_translate("Dialog", "E", None))
        item = self.srclistWidget.item(5)
        item.setText(_translate("Dialog", "F", None))
        item = self.srclistWidget.item(6)
        item.setText(_translate("Dialog", "G", None))
        self.srclistWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.dstlistWidget.isSortingEnabled()
        self.dstlistWidget.setSortingEnabled(False)
        item = self.dstlistWidget.item(0)
        item.setText(_translate("Dialog", "A", None))
        item = self.dstlistWidget.item(1)
        item.setText(_translate("Dialog", "B", None))
        item = self.dstlistWidget.item(2)
        item.setText(_translate("Dialog", "C", None))
        item = self.dstlistWidget.item(3)
        item.setText(_translate("Dialog", "D", None))
        item = self.dstlistWidget.item(4)
        item.setText(_translate("Dialog", "E", None))
        item = self.dstlistWidget.item(5)
        item.setText(_translate("Dialog", "F", None))
        item = self.dstlistWidget.item(6)
        item.setText(_translate("Dialog", "G", None))
        self.dstlistWidget.setSortingEnabled(__sortingEnabled)
        self.lineLabel.setText(_translate("Dialog", "LINE: ", None))
        self.stateLabel.setText(_translate("Dialog", "State", None))
        self.intersectionLabel.setText(_translate("Dialog", "Intersection", None))
        self.batteryLabel.setText(_translate("Dialog", "Battery: ", None))
        self.modeLabel.setText(_translate("Dialog", "Mode", None))
        self.sonarLabel.setText(_translate("Dialog", "Sonar", None))

